// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sfs
arma::Row<int> sfs(SEXP dissimilarity);
RcppExport SEXP SFS_sfs(SEXP dissimilaritySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dissimilarity(dissimilaritySEXP);
    rcpp_result_gen = Rcpp::wrap(sfs(dissimilarity));
    return rcpp_result_gen;
END_RCPP
}
