# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sfs <- function(dissimilarity, zero_eps = 1.0e-200) {
    .Call('SFS_sfs', PACKAGE = 'SFS', dissimilarity, zero_eps)
}

